language: node_js
dist: trusty
sudo: false
node_js:
  - "8"
  - "10"
before_install:
  - npm install -g npm@latest
install:
  - npm ci
after_success:
  - npm run coverage
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
notifications:
  email: false
